[package]
name = "jss"
version = "0.1.0"
authors = ["Anton Shramko <antonshramko@yandex.ru>"]
repository = "https://github.com/rise-ui/jss-rs"
homepage = "https://github.com/rise-ui/jss-rs"
description = "Rust implementation of JSS"
keywords = ["gui", "layout", "yoga", "jss", "parsing", "rise-ui"]
readme = "README.md"
categories = ["gui"]
license = "MIT"

[features]
webrender_support = []
default = []

[dependencies]
webrender = { rev = "c540acf0990f8a0cbf9429e7085c7cc3b6901add", git = "https://github.com/servo/webrender" }
serde_derive = { version = "=1.0.66", features = ["deserialize_in_place"] }
yoga = { version = "0.2", features = ["serde_support"] }
euclid = { version = "0.17", features = ["serde"] }
serde = { version = "=1.0.66", features = ["rc"] }
css-color-parser = "0.1"
ordered-float = "0.5.0"
failure_derive = "0.1"
jss_derive = "0.1.0"
enum_extract = "0.1"
lazy_static = "1.0"
serde_json = "1.0"
failure = "0.1"
regex = "0.2"
nom = "4.0"