[package]
name = "jss"
version = "0.1.0"
authors = ["Anton Shramko <antonshramko@yandex.ru>"]
repository = "https://github.com/rise-ui/jss-rs"
homepage = "https://github.com/rise-ui/jss-rs"
description = "Rust implementation of JSS"
keywords = ["gui", "layout", "yoga", "jss", "parsing"]
categories = ["gui"]
license = "MIT"

[features]
default = []
webrender_support = []

[workspace]

[dependencies]
webrender = { rev = "34a498f7e46c385a189299e7369e204e1cb2060c", git = "https://github.com/servo/webrender" }
yoga = { git = "https://github.com/rise-ui/yoga-rs", features = ["serde_support"] }
prepare-style-derive = { path = "prepare-style-derive", version = "0.1.0" }
serde_derive = { version = "=1.0.66", features = ["deserialize_in_place"] }
serde = { version = "=1.0.66", features = ["rc"] }
euclid = { version = "0.17", features = ["serde"] }
ordered-float = "0.5.0"
css-color-parser = "*"
failure_derive = "0.1"
enum_extract = "0.1"
lazy_static = "1.0"
serde_json = "1.0"
failure = "0.1"
regex = "0.2"
nom = "4.0"