[package]
keywords = ["gui", "layout", "yoga", "jss", "parsing", "rise-ui"]
authors = ["Anton Shramko <antonshramko@yandex.ru>"]
repository = "https://github.com/rise-ui/jss-rs"
homepage = "https://github.com/rise-ui/jss-rs"
description = "Rust implementation of JSS"
categories = ["gui"]
readme = "README.md"
version = "0.1.0"
license = "MIT"
name = "jss"

[dependencies]
serde_derive = { version = "1.0.73", features = ["deserialize_in_place"] }
jss_derive = { git = "https://github.com/rise-ui/jss_derive", version = "0.1.0", branch="refactoring" }
# jss_derive = { path = "./jss_derive", version = "0.1.0" }
yoga = { version = "0.2", features = ["serde_support"] }
euclid = { version = "0.19.0", features = ["serde"] }
serde = { version = "1.0.73", features = ["rc"] }
css-color-parser = "0.1.2"
failure_derive = "0.1.2"
ordered-float = "0.5.0"
enum_extract = "0.1.1"
lazy_static = "1.1.0"
serde_json = "1.0.26"
serde_yaml = "0.8.0"
Inflector = "0.11.3"
failure = "0.1.2"
maplit = "1.0.1"
regex = "1.0.2"
nom = "4.0.0"
